const CONFIRM_EMOJI = '✅';
const DECLINE_EMOJI = '❌';

const ONE_MINUTE = 1000 * 60;
const CONFIRMATION_DEFAULT_TIMEOUT = 30 * 1000;
const INTERACTION_MAX_TIMEOUT = ONE_MINUTE * 14;

const DIGITS_REGEX = /^\d+$/;
const CHANNEL_ARG_REGEX = /^<#\d+>$/;

const Colors = Object.freeze({
   SUCCESS: '#208637',
   WARN: '#FFC107',
   DANGER: '#F44336',
});

const BULK_MESSAGES_LIMIT = 100;
const MAX_MESSAGES_FETCH = 500;

const MIN_REMINDER_INTERVAL = 10 * 60;
const WAKE_INTERVAL = 10 * 60 * 1000;
const MESSAGE_PREVIEW_LENGTH = 50;

const YT_PLAYLIST_PAGE_SIZE = 50;
const MAX_YT_PLAYLIST_PAGE_FETCHES = 4;

const SPOTIFY_PLAYLIST_PAGE_SIZE = 50;
const MAX_SPOTIFY_PLAYLIST_PAGE_FETCHES = 4;

const CONCURRENCY_LIMIT = 10;

module.exports = {
   CONFIRM_EMOJI,
   DECLINE_EMOJI,
   ONE_MINUTE,
   CONFIRMATION_DEFAULT_TIMEOUT,
   INTERACTION_MAX_TIMEOUT,
   DIGITS_REGEX,
   CHANNEL_ARG_REGEX,
   Colors,
   BULK_MESSAGES_LIMIT,
   MAX_MESSAGES_FETCH,
   MIN_REMINDER_INTERVAL,
   WAKE_INTERVAL,
   MESSAGE_PREVIEW_LENGTH,
   YT_PLAYLIST_PAGE_SIZE,
   MAX_YT_PLAYLIST_PAGE_FETCHES,
   SPOTIFY_PLAYLIST_PAGE_SIZE,
   MAX_SPOTIFY_PLAYLIST_PAGE_FETCHES,
   CONCURRENCY_LIMIT,
};
